// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlYfZvn71oErKGmMBP9YFRiavoknElUns',
    appId: '1:722438426805:web:53f00c8a9472497519aefc',
    messagingSenderId: '722438426805',
    projectId: 'pose-c08f4',
    authDomain: 'pose-c08f4.firebaseapp.com',
    storageBucket: 'pose-c08f4.appspot.com',
    measurementId: 'G-422FJ22RTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfScJUvR4ka_759eHqO2qkwViRMstIIwQ',
    appId: '1:722438426805:android:789f4c1c41a0824919aefc',
    messagingSenderId: '722438426805',
    projectId: 'pose-c08f4',
    storageBucket: 'pose-c08f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Tk4DAP7jpFUFON-_G_vM2LUsL_szseI',
    appId: '1:722438426805:ios:8ea3a20427ed759319aefc',
    messagingSenderId: '722438426805',
    projectId: 'pose-c08f4',
    storageBucket: 'pose-c08f4.appspot.com',
    iosBundleId: 'com.example.poseEstimation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Tk4DAP7jpFUFON-_G_vM2LUsL_szseI',
    appId: '1:722438426805:ios:eb37c0d48c28455d19aefc',
    messagingSenderId: '722438426805',
    projectId: 'pose-c08f4',
    storageBucket: 'pose-c08f4.appspot.com',
    iosBundleId: 'com.example.poseEstimation.RunnerTests',
  );
}
